#!/usr/bin/env python3
"""
build_binary_vs_decoder_shared_ref_v3.py — shared-reference decoder vs.
categorical-baseline comparison (Table in Section "Binary baseline").

FIX (Round 4 review follow-up, found while updating that table): the
file this table used, results/binary_vs_decoder_shared_ref_v3.json, was
NOT generated by any script in code/ (verified: no file references it as
an output) and was dated 2026-07-21 -- an orphaned artefact from an
earlier round that was never regenerated through any of the Round 3/4
fixes (still showed npar=104+/-0 for the decoder, the exact pre-dedup
convention this round's dedup_front() fix corrected everywhere else).
This script reconstructs it properly, deduplicated, from the current
checkpoint/results files, so it stops being a silently-stale number.

Reads: results/step1_baselines_v3/{nsga2,nsga3}_seed*.pkl (decoder,
already deduplicated per-run by dedup_front in run_baselines_comparison_v3.py)
and results/binary_baseline_v3_results.json (categorical, already
deduplicated per-run in binary_baseline_v3.py).
Writes: results/binary_vs_decoder_shared_ref_v3.json
"""
import json
import pickle
import numpy as np
from metrics import compute_spacing
from pathlib import Path

from pymoo.util.nds.non_dominated_sorting import find_non_dominated
from pymoo.indicators.hv import Hypervolume
from pymoo.indicators.igd import IGD

from bdcz_oracle_v3 import dedup_front

RESULTS = Path(__file__).resolve().parent.parent / 'results'
HV_REF = np.array([1.1] * 4)
SEEDS = list(range(42, 72))  # FIX (external review round 6-followup): both the
                             # decoder and the categorical baseline now have 30
                             # seeds each (was 10) -- this table's own reference
                             # front and both sides' per-run metrics are rebuilt
                             # from the full 30, not the first 10, of each.




# ── Load decoder per-seed fronts (already deduplicated) ────────────────────
decoder_fronts = {'nsga2': [], 'nsga3': []}
for algo in ['nsga2', 'nsga3']:
    for seed in SEEDS:
        p = RESULTS / 'step1_baselines_v3' / f'{algo}_seed{seed}.pkl'
        with open(p, 'rb') as fh:
            run = pickle.load(fh)
        decoder_fronts[algo].append(run['F_pareto'])

# ── Load categorical per-seed fronts (already deduplicated) ────────────────
with open(RESULTS / 'binary_baseline_v3_results.json') as f:
    bb = json.load(f)
categorical_fronts = {'nsga2': [], 'nsga3': []}
for algo, key in [('nsga2', 'nsga2_categorical'), ('nsga3', 'nsga3_categorical')]:
    for entry in bb[key]:
        categorical_fronts[algo].append(np.array(entry['pareto_front']))

# ── Shared reference front: pool everything, non-dominated, deduplicated ───
all_F = ([F for fs in decoder_fronts.values() for F in fs if len(F) > 0] +
         [F for fs in categorical_fronts.values() for F in fs if len(F) > 0])
combined = np.vstack(all_F)
g_min, g_max = combined.min(axis=0), combined.max(axis=0)
g_range = np.where((g_max - g_min) < 1e-12, 1e-9, g_max - g_min)


def normalise(F):
    return (F - g_min) / g_range


nd_global = find_non_dominated(combined)
ref_raw, _ = dedup_front(combined[nd_global], combined[nd_global])
ref_front = normalise(ref_raw)
hv_calc, igd_calc = Hypervolume(ref_point=HV_REF), IGD(ref_front)
print(f'Shared reference front: {len(combined)} pooled -> '
      f'{len(combined[nd_global])} non-dominated -> {len(ref_front)} deduplicated')


def summarize(fronts):
    hv_l, igd_l, sp_l, npar_l = [], [], [], []
    for F in fronts:
        if len(F) == 0:
            continue
        Fn = normalise(F)
        hv_l.append(float(hv_calc(Fn)))
        igd_l.append(float(igd_calc(Fn)))
        sp_l.append(compute_spacing(Fn))
        npar_l.append(len(F))
    # ddof=1 (sample std, matching every other script this round -- was
    # ddof=0 here, missed in the original Round 6 ddof=1 pass).
    return {
        'hv_mean': float(np.mean(hv_l)), 'hv_std': float(np.std(hv_l, ddof=1)),
        'igd_mean': float(np.mean(igd_l)), 'igd_std': float(np.std(igd_l, ddof=1)),
        'spacing_mean': float(np.mean(sp_l)), 'spacing_std': float(np.std(sp_l, ddof=1)),
        'npar_mean': float(np.mean(npar_l)), 'npar_std': float(np.std(npar_l, ddof=1)),
    }


output = {
    'decoder_nsga2': summarize(decoder_fronts['nsga2']),
    'decoder_nsga3': summarize(decoder_fronts['nsga3']),
    'categorical_nsga2': summarize(categorical_fronts['nsga2']),
    'categorical_nsga3': summarize(categorical_fronts['nsga3']),
    'note': ('All four rows computed against the SAME shared, deduplicated '
             'reference front (pooled decoder + categorical, all seeds), '
             'so HV/IGD are directly comparable across rows. npar is each '
             'condition\'s own deduplicated per-run cardinality, mean/std '
             'over 30 seeds.'),
}
with open(RESULTS / 'binary_vs_decoder_shared_ref_v3.json', 'w') as f:
    json.dump(output, f, indent=2)
print(json.dumps(output, indent=2))
print(f"\nSaved: {RESULTS / 'binary_vs_decoder_shared_ref_v3.json'}")
